import type { RuntimeCapabilityDefinition } from "./types.ts";

const internalDiagnosticInputSchema = {
  $id: "aios://capabilities/internal-runtime-diagnostic/input/1.2.0",
  type: "object",
  additionalProperties: true,
  properties: {
    governed_write_probe: {
      type: "object",
      additionalProperties: false,
      properties: {
        write_authorized: { type: "boolean" },
        write_policy_refs: { type: "array", items: { type: "string" } },
        mason_episode_id: { type: "string" },
        write_plan_id: { type: "string" },
        authorization_id: { type: "string" },
        execution_receipt_id: { type: "string" },
        destination: { type: "string" },
      },
      required: [
        "write_authorized",
        "write_policy_refs",
        "mason_episode_id",
        "write_plan_id",
        "authorization_id",
        "execution_receipt_id",
        "destination",
      ],
    },
  },
} as const;

const internalDiagnosticOutputSchema = {
  $id: "aios://capabilities/internal-runtime-diagnostic/output/1.2.0",
  type: "object",
  additionalProperties: true,
  properties: {
    validated: { type: "boolean" },
    input_keys: { type: "array", items: { type: "string" } },
    input_property_count: { type: "integer" },
    input_bytes: { type: "integer" },
    input_sha256: { type: "string" },
    diagnostic: { const: "PASS" },
    executed_on: { const: "server" },
    handler_version: { type: "string" },
    finished_at: { type: "string" },
    external_systems_accessed: { type: "array", items: { type: "string" } },
    governed_write_probe: { type: "object" },
  },
} as const;

const capabilityDiscoveryInputSchema = {
  $id: "aios://capabilities/capability-discovery/input/1.1.0",
  type: "object",
  additionalProperties: false,
  required: ["action", "scope_key", "mode", "intent_class"],
  properties: {
    action: { const: "discover" },
    execution_id: { type: "string", minLength: 1 },
    workflow_id: { type: "string", minLength: 1 },
    scope_key: { type: "string", minLength: 1 },
    mode: { enum: ["LIVE", "SIMULATION"] },
    intent_class: { type: "string", minLength: 1 },
    intent_text: { type: "string", minLength: 1 },
    authority_domains: { type: "array", items: { type: "string", minLength: 1 } },
    requested_capability_id: { type: "string", minLength: 1 },
  },
} as const;

const capabilityDiscoveryOutputSchema = {
  $id: "aios://capabilities/capability-discovery/output/1.1.0",
  type: "object",
  additionalProperties: false,
  required: [
    "envelope",
    "selection",
    "materialized_capability",
    "events",
    "persistence",
    "execution_authority",
    "requested_by",
  ],
  properties: {
    envelope: { type: "object" },
    selection: { type: ["object", "null"] },
    materialized_capability: { type: ["object", "null"] },
    events: { type: "array", items: { type: "object" } },
    persistence: { const: "PROCESS_LOCAL" },
    execution_authority: { const: "NONE" },
    requested_by: { type: ["string", "null"] },
  },
} as const;

const repositoryContextRetrievalInputSchema = {
  $id: "aios://capabilities/repository-context-retrieval/input/1.0.0",
  type: "object",
  additionalProperties: false,
  required: ["request_text", "requested_scope"],
  properties: {
    request_text: { type: "string", minLength: 1 },
    requested_scope: { type: "string", minLength: 1 },
  },
} as const;

const repositoryContextRetrievalOutputSchema = {
  $id: "aios://capabilities/repository-context-retrieval/output/1.0.0",
  type: "object",
  additionalProperties: true,
  required: ["trace_id", "status", "packet", "result", "receipt"],
  properties: {
    trace_id: { type: "string", minLength: 1 },
    status: { enum: ["COMPLETED", "FAILED"] },
    packet: { type: ["object", "null"] },
    result: { type: ["object", "null"] },
    receipt: { type: ["object", "null"] },
  },
} as const;

export const internalRuntimeDiagnosticCapability: RuntimeCapabilityDefinition = {
  schema_name: "RuntimeCapabilityDefinition",
  schema_version: "1.0",
  capability_id: "cap:internal-runtime-diagnostic",
  name: "Internal Runtime Diagnostic",
  description: "Runs the native server diagnostic workflow and emits execution-local provenance without claiming external system access.",
  workflow_id: "internal-runtime-diagnostic",
  version: "1.2.0",
  status: "ACTIVE",
  discoverable: true,
  intent_classes: ["runtime-diagnostic", "workflow-kernel-diagnostic", "system-health-check"],
  positive_examples: [
    "check the server workflow kernel",
    "run an internal runtime diagnostic",
    "verify process-local execution and provenance",
  ],
  negative_examples: ["write project canon", "update notion memory", "modify repository code"],
  overlap_group: "runtime-diagnostics",
  precedence_priority: 100,
  preferred_over: [],
  scope_allowlist: ["*"],
  scope_denylist: [],
  authority_domains: ["server-runtime-execution-state", "execution-local-input"],
  input_schema_ref: "aios://capabilities/internal-runtime-diagnostic/input/1.2.0",
  output_schema_ref: "aios://capabilities/internal-runtime-diagnostic/output/1.2.0",
  input_schema: internalDiagnosticInputSchema,
  output_schema: internalDiagnosticOutputSchema,
  expected_schema_fingerprint: "sha256:cd45b0584f21b84a9c8597b8cbdd16a2e9a2f703041064f8fc17ea80b6874542",
  handler_ref: "workflow:internal-runtime-diagnostic",
  trust_level: "INTERNAL_NATIVE",
  data_access: "EXECUTION_LOCAL",
  reversibility: "FULLY_REVERSIBLE",
  blast_radius: "PROCESS_LOCAL",
  autonomy_band: "A0",
  approval_required: false,
  materialization_requires_approval: false,
  execution_modes: ["LIVE"],
  health: {
    status: "VERIFIED",
    checked_at: "2026-07-24T02:32:20.000Z",
    expires_at: null,
    verification_source: "registered native handler + repository CI",
  },
  source_authority: "GITHUB_EXECUTION_TRUTH",
};

export const capabilityDiscoveryCapability: RuntimeCapabilityDefinition = {
  schema_name: "RuntimeCapabilityDefinition",
  schema_version: "1.0",
  capability_id: "cap:capability-discovery",
  name: "Dynamic Capability Discovery",
  description: "Resolves exact intent and scope against registered runtime metadata, rejects ineligible candidates, and returns a process-local discovery snapshot without authorizing execution.",
  workflow_id: "capability-discovery",
  version: "1.1.0",
  status: "ACTIVE",
  discoverable: true,
  intent_classes: ["capability-discovery", "tool-routing", "find-capability", "schema-materialization"],
  positive_examples: [
    "find the registered capability for this task",
    "discover tools for an exact scope",
    "prepare the selected capability for schema materialization",
    "check capability overlap before building",
  ],
  negative_examples: ["execute the discovered tool immediately", "authorize a destination write", "promote memory to canon"],
  overlap_group: "capability-routing",
  precedence_priority: 100,
  preferred_over: [],
  scope_allowlist: ["*"],
  scope_denylist: [],
  authority_domains: ["server-runtime-execution-state", "runtime-capability-registry"],
  input_schema_ref: "aios://capabilities/capability-discovery/input/1.1.0",
  output_schema_ref: "aios://capabilities/capability-discovery/output/1.1.0",
  input_schema: capabilityDiscoveryInputSchema,
  output_schema: capabilityDiscoveryOutputSchema,
  expected_schema_fingerprint: "sha256:ce47b1be22de546df9a4ca55bc07dd30b3be1d7e227608853b981004a36fd94e",
  handler_ref: "api:/api/capabilities#discover",
  trust_level: "INTERNAL_NATIVE",
  data_access: "EXECUTION_LOCAL",
  reversibility: "FULLY_REVERSIBLE",
  blast_radius: "PROCESS_LOCAL",
  autonomy_band: "A0",
  approval_required: false,
  materialization_requires_approval: false,
  execution_modes: ["LIVE"],
  health: {
    status: "VERIFIED",
    checked_at: "2026-07-26T13:00:00.000Z",
    expires_at: null,
    verification_source: "native API discover action; CI required before merge",
  },
  source_authority: "GITHUB_EXECUTION_TRUTH",
};

export const repositoryContextRetrievalCapability: RuntimeCapabilityDefinition = {
  schema_name: "RuntimeCapabilityDefinition",
  schema_version: "1.0",
  capability_id: "cap:repository-context-retrieval",
  name: "Repository Context Retrieval",
  description: "Resolves the global AIOS scope, retrieves current repository execution facts, assembles a bounded context packet, and emits a performance receipt.",
  workflow_id: "repository-context-query",
  version: "1.0.0",
  status: "ACTIVE",
  discoverable: true,
  intent_classes: ["repository-context-retrieval", "aios-runtime-query", "runtime-observability"],
  positive_examples: [
    "show the current AIOS runtime components",
    "retrieve repository execution facts for AI_MEMORY_OS",
    "run the observable context packet route",
  ],
  negative_examples: ["write project canon", "update external memory", "execute a repository mutation"],
  overlap_group: "context-retrieval",
  precedence_priority: 110,
  preferred_over: [],
  scope_allowlist: ["global-working-memory"],
  scope_denylist: [],
  authority_domains: ["github-repository-execution-truth"],
  input_schema_ref: "aios://capabilities/repository-context-retrieval/input/1.0.0",
  output_schema_ref: "aios://capabilities/repository-context-retrieval/output/1.0.0",
  input_schema: repositoryContextRetrievalInputSchema,
  output_schema: repositoryContextRetrievalOutputSchema,
  expected_schema_fingerprint: "sha256:40dc729827ce5d9f62e0da2fd5a00662602cc8abe0090a9fabfee15a1e1c3c16",
  handler_ref: "api:/api/aios-runtime",
  trust_level: "INTERNAL_NATIVE",
  data_access: "EXECUTION_LOCAL",
  reversibility: "FULLY_REVERSIBLE",
  blast_radius: "PROCESS_LOCAL",
  autonomy_band: "A0",
  approval_required: false,
  materialization_requires_approval: false,
  execution_modes: ["LIVE"],
  health: {
    status: "VERIFIED",
    checked_at: "2026-08-08T00:00:00.000Z",
    expires_at: null,
    verification_source: "native API route + repository-backed source adapter + CI",
  },
  source_authority: "GITHUB_EXECUTION_TRUTH",
};
