export const compiledPublicRegistry = {
  schema_name: "CompiledAiosRegistry",
  schema_version: "1.0",
  registry_version: "0.1.0-phase1",
  routing_precedence: [
    "EXACT_SCOPE_KEY",
    "EXACT_PROJECT_NAME",
    "REGISTERED_ALIAS",
    "EXPLICIT_PARENT_SUBPROJECT",
    "BOUNDED_CONTINUITY",
    "AMBIGUITY_OR_NO_MATCH",
  ],
  routing_tables: {
    exact_scope_keys: { "global-runtime": "global-runtime" },
    exact_project_names: { "global runtime": "global-runtime" },
    exact_aliases: { "core-runtime": "global-runtime" },
    children_by_parent: {},
  },
  scopes: [
    {
      schema_name: "ScopeDefinition",
      schema_version: "1.0",
      scope_key: "global-runtime",
      project_name: "Global Runtime",
      parent_scope_key: null,
      status: "ACTIVE",
      description: "Provider-neutral synthetic root scope for the public starter registry.",
      health: {
        status: "VERIFIED",
        checked_at: "2026-07-26T00:00:00.000Z",
        expires_at: null,
      },
    },
  ],
  aliases: [
    {
      schema_name: "AliasDefinition",
      schema_version: "1.0",
      alias_id: "alias:global-runtime:core",
      alias: "core-runtime",
      scope_key: "global-runtime",
      status: "ACTIVE",
    },
  ],
  capabilities: [
    {
      schema_name: "RuntimeCapabilityDefinition",
      schema_version: "1.0",
      capability_id: "cap:capability-discovery",
      name: "Dynamic Capability Discovery",
      description: "Resolves exact intent and scope against registered runtime metadata, rejects ineligible candidates, and returns a process-local discovery snapshot without authorizing execution.",
      workflow_id: "capability-discovery",
      version: "1.1.0",
      status: "ACTIVE",
      discoverable: true,
      intent_classes: ["capability-discovery", "tool-routing", "find-capability", "schema-materialization"],
      positive_examples: [
        "find the registered capability for this task",
        "discover tools for an exact scope",
        "prepare the selected capability for schema materialization",
        "check capability overlap before building",
      ],
      negative_examples: [
        "execute the discovered tool immediately",
        "authorize a destination write",
        "promote memory to canon",
      ],
      overlap_group: "capability-routing",
      precedence_priority: 100,
      preferred_over: [],
      scope_allowlist: ["*"],
      scope_denylist: [],
      authority_domains: ["server-runtime-execution-state", "runtime-capability-registry"],
      input_schema_ref: "aios://capabilities/capability-discovery/input/1.1.0",
      output_schema_ref: "aios://capabilities/capability-discovery/output/1.1.0",
      input_schema: {
        $id: "aios://capabilities/capability-discovery/input/1.1.0",
        type: "object",
        additionalProperties: false,
        required: ["action", "scope_key", "mode", "intent_class"],
        properties: {
          action: { const: "discover" },
          execution_id: { type: "string", minLength: 1 },
          workflow_id: { type: "string", minLength: 1 },
          scope_key: { type: "string", minLength: 1 },
          mode: { enum: ["LIVE", "SIMULATION"] },
          intent_class: { type: "string", minLength: 1 },
          intent_text: { type: "string", minLength: 1 },
          authority_domains: {
            type: "array",
            items: { type: "string", minLength: 1 },
          },
          requested_capability_id: { type: "string", minLength: 1 },
        },
      },
      output_schema: {
        $id: "aios://capabilities/capability-discovery/output/1.1.0",
        type: "object",
        additionalProperties: false,
        required: [
          "envelope",
          "selection",
          "materialized_capability",
          "events",
          "persistence",
          "execution_authority",
          "requested_by",
        ],
        properties: {
          envelope: { type: "object" },
          selection: { type: ["object", "null"] },
          materialized_capability: { type: ["object", "null"] },
          events: { type: "array", items: { type: "object" } },
          persistence: { const: "PROCESS_LOCAL" },
          execution_authority: { const: "NONE" },
          requested_by: { type: ["string", "null"] },
        },
      },
      expected_schema_fingerprint: "sha256:ce47b1be22de546df9a4ca55bc07dd30b3be1d7e227608853b981004a36fd94e",
      handler_ref: "api:/api/capabilities#discover",
      trust_level: "INTERNAL_NATIVE",
      data_access: "EXECUTION_LOCAL",
      reversibility: "FULLY_REVERSIBLE",
      blast_radius: "PROCESS_LOCAL",
      autonomy_band: "A0",
      approval_required: false,
      materialization_requires_approval: false,
      execution_modes: ["LIVE"],
      health: {
        status: "VERIFIED",
        checked_at: "2026-07-26T13:00:00.000Z",
        expires_at: null,
        verification_source: "native API discover action; repository CI",
      },
      source_authority: "GITHUB_EXECUTION_TRUTH",
    },
    {
      schema_name: "RuntimeCapabilityDefinition",
      schema_version: "1.0",
      capability_id: "cap:internal-runtime-diagnostic",
      name: "Internal Runtime Diagnostic",
      description: "Runs the native server diagnostic workflow without external provider access.",
      workflow_id: "internal-runtime-diagnostic",
      version: "1.2.0",
      status: "ACTIVE",
      discoverable: true,
      intent_classes: ["runtime-diagnostic", "system-health-check"],
      positive_examples: ["run an internal runtime diagnostic"],
      negative_examples: ["write project canon"],
      overlap_group: "runtime-diagnostics",
      precedence_priority: 100,
      preferred_over: [],
      scope_allowlist: ["*"],
      scope_denylist: [],
      authority_domains: ["server-runtime-execution-state"],
      input_schema_ref: "aios://capabilities/internal-runtime-diagnostic/input/1.2.0",
      output_schema_ref: "aios://capabilities/internal-runtime-diagnostic/output/1.2.0",
      input_schema: {
        $id: "aios://capabilities/internal-runtime-diagnostic/input/1.2.0",
        type: "object",
        additionalProperties: true,
      },
      output_schema: {
        $id: "aios://capabilities/internal-runtime-diagnostic/output/1.2.0",
        type: "object",
        additionalProperties: true,
        properties: { validated: { type: "boolean" } },
      },
      expected_schema_fingerprint: "sha256:77378d6648bfb17e402e30bb5516cec546ad5e6a07228aeebe85906fd111cda6",
      handler_ref: "workflow:internal-runtime-diagnostic",
      trust_level: "INTERNAL_NATIVE",
      data_access: "EXECUTION_LOCAL",
      reversibility: "FULLY_REVERSIBLE",
      blast_radius: "PROCESS_LOCAL",
      autonomy_band: "A0",
      approval_required: false,
      materialization_requires_approval: false,
      execution_modes: ["LIVE"],
      health: {
        status: "VERIFIED",
        checked_at: "2026-07-26T00:00:00.000Z",
        expires_at: null,
        verification_source: "registered native handler",
      },
      source_authority: "GITHUB_EXECUTION_TRUTH",
    },
  ],
  workflows: [
    {
      schema_name: "WorkflowRegistryEntry",
      schema_version: "1.0",
      workflow_id: "capability-discovery",
      version: "1.1.0",
      status: "ACTIVE",
      handler_ref: "api:/api/capabilities#discover",
      handler_available: true,
      execution_modes: ["LIVE"],
      scope_policy: "EXACT_INHERITANCE",
      next_action_policy: "NONE",
    },
    {
      schema_name: "WorkflowRegistryEntry",
      schema_version: "1.0",
      workflow_id: "internal-runtime-diagnostic",
      version: "1.2.0",
      status: "ACTIVE",
      handler_ref: "workflow:internal-runtime-diagnostic",
      handler_available: true,
      execution_modes: ["LIVE"],
      scope_policy: "EXACT_INHERITANCE",
      next_action_policy: "REGISTRY_BACKED",
    },
  ],
  authority: [
    {
      schema_name: "AuthorityBinding",
      schema_version: "1.0",
      binding_id: "authority:global-runtime:execution",
      scope_key: "global-runtime",
      authority_domain: "server-runtime-execution-state",
      authority_role: "GITHUB_EXECUTION_TRUTH",
      read_from: ["REPOSITORY_RUNTIME"],
      write_authorized: false,
      status: "ACTIVE",
    },
  ],
  registry_fingerprint: "sha256:a5a2a993ab6460a85b29dede38f9adbb57606b3e6fd35f12fe22a55f92a1ae92",
  inventory_projection_fingerprint: "sha256:7ce992c36e023b576401c2473c4223c8e883863efca385db4247b35b4ba3572c",
} as const;
