export const compiledPublicRegistry = {
  schema_name: "CompiledAiosRegistry",
  schema_version: "1.0",
  registry_version: "0.1.0-phase1",
  routing_precedence: [
    "EXACT_SCOPE_KEY",
    "EXACT_PROJECT_NAME",
    "REGISTERED_ALIAS",
    "EXPLICIT_PARENT_SUBPROJECT",
    "BOUNDED_CONTINUITY",
    "AMBIGUITY_OR_NO_MATCH",
  ],
  routing_tables: {
    exact_scope_keys: { "global-runtime": "global-runtime" },
    exact_project_names: { "global runtime": "global-runtime" },
    exact_aliases: { "core-runtime": "global-runtime" },
    children_by_parent: {},
  },
  scopes: [
    {
      schema_name: "ScopeDefinition",
      schema_version: "1.0",
      scope_key: "global-runtime",
      project_name: "Global Runtime",
      parent_scope_key: null,
      status: "ACTIVE",
      description: "Provider-neutral synthetic root scope for the public starter registry.",
      health: {
        status: "VERIFIED",
        checked_at: "2026-07-26T00:00:00.000Z",
        expires_at: null,
      },
    },
  ],
  aliases: [
    {
      schema_name: "AliasDefinition",
      schema_version: "1.0",
      alias_id: "alias:global-runtime:core",
      alias: "core-runtime",
      scope_key: "global-runtime",
      status: "ACTIVE",
    },
  ],
  capabilities: [
    {
      schema_name: "RuntimeCapabilityDefinition",
      schema_version: "1.0",
      capability_id: "cap:internal-runtime-diagnostic",
      name: "Internal Runtime Diagnostic",
      description: "Runs the native server diagnostic workflow without external provider access.",
      workflow_id: "internal-runtime-diagnostic",
      version: "1.2.0",
      status: "ACTIVE",
      discoverable: true,
      intent_classes: ["runtime-diagnostic", "system-health-check"],
      positive_examples: ["run an internal runtime diagnostic"],
      negative_examples: ["write project canon"],
      overlap_group: "runtime-diagnostics",
      precedence_priority: 100,
      preferred_over: [],
      scope_allowlist: ["global-runtime"],
      scope_denylist: [],
      authority_domains: ["server-runtime-execution-state"],
      input_schema_ref: "aios://capabilities/internal-runtime-diagnostic/input/1.2.0",
      output_schema_ref: "aios://capabilities/internal-runtime-diagnostic/output/1.2.0",
      input_schema: {
        $id: "aios://capabilities/internal-runtime-diagnostic/input/1.2.0",
        type: "object",
        additionalProperties: true,
      },
      output_schema: {
        $id: "aios://capabilities/internal-runtime-diagnostic/output/1.2.0",
        type: "object",
        additionalProperties: true,
        properties: { validated: { type: "boolean" } },
      },
      expected_schema_fingerprint: "sha256:77378d6648bfb17e402e30bb5516cec546ad5e6a07228aeebe85906fd111cda6",
      handler_ref: "workflow:internal-runtime-diagnostic",
      trust_level: "INTERNAL_NATIVE",
      data_access: "EXECUTION_LOCAL",
      reversibility: "FULLY_REVERSIBLE",
      blast_radius: "PROCESS_LOCAL",
      autonomy_band: "A0",
      approval_required: false,
      materialization_requires_approval: false,
      execution_modes: ["LIVE"],
      health: {
        status: "VERIFIED",
        checked_at: "2026-07-26T00:00:00.000Z",
        expires_at: null,
        verification_source: "registered native handler",
      },
      source_authority: "GITHUB_EXECUTION_TRUTH",
    },
  ],
  workflows: [
    {
      schema_name: "WorkflowRegistryEntry",
      schema_version: "1.0",
      workflow_id: "internal-runtime-diagnostic",
      version: "1.2.0",
      status: "ACTIVE",
      handler_ref: "workflow:internal-runtime-diagnostic",
      handler_available: true,
      execution_modes: ["LIVE"],
      scope_policy: "EXACT_INHERITANCE",
      next_action_policy: "REGISTRY_BACKED",
    },
  ],
  authority: [
    {
      schema_name: "AuthorityBinding",
      schema_version: "1.0",
      binding_id: "authority:global-runtime:execution",
      scope_key: "global-runtime",
      authority_domain: "server-runtime-execution-state",
      authority_role: "GITHUB_EXECUTION_TRUTH",
      read_from: ["REPOSITORY_RUNTIME"],
      write_authorized: false,
      status: "ACTIVE",
    },
  ],
  registry_fingerprint: "sha256:446986ca2fb2f6a841ae775b9501722eaf6cd3a110070aacc903297a2182a11c",
  inventory_projection_fingerprint: "sha256:2662341bb09403447328c6f72286b0a8e7baadbc99a4a581c0bb2608952e624e",
} as const;
